# Generated by Django 5.2 on 2025-04-19 14:46

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this model instance.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the instance was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the instance was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='ACTIVE', help_text='Status of the instance, typically used for soft deletion.', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography of the user')),
                ('badge', models.CharField(blank=True, help_text="User's badge or title", max_length=250)),
                ('profile_photo', models.URLField(blank=True, help_text='URL to the profile photo', max_length=500)),
                ('contact_number', models.CharField(blank=True, help_text="User's contact number", max_length=15)),
                ('contact_email', models.EmailField(blank=True, help_text="User's contact email", max_length=255)),
                ('location', models.CharField(blank=True, help_text="User's location", max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('facebook_link', models.URLField(blank=True, help_text='Facebook profile link', max_length=500)),
                ('twitter_link', models.URLField(blank=True, help_text='Twitter profile link', max_length=500)),
                ('instagram_link', models.URLField(blank=True, help_text='Instagram profile link', max_length=500)),
                ('linkedin_link', models.URLField(blank=True, help_text='LinkedIn profile link', max_length=500)),
                ('youtube_link', models.URLField(blank=True, help_text='YouTube channel link', max_length=500)),
                ('website_link', models.URLField(blank=True, help_text='Personal website link', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
