# Generated by Django 5.2 on 2025-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='about_me_text',
            field=models.TextField(blank=True, help_text='Content of about me tab for the user'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='gallery_text',
            field=models.TextField(blank=True, help_text='Content of gallery tab for the user'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='visited_place_text',
            field=models.TextField(blank=True, help_text='Content of visited place tab for the user'),
        ),
    ]
