# Generated by Django 5.2 on 2025-04-19 17:18

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userdetail_about_me_text_userdetail_gallery_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='about_me_text',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='gallery_text',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='visited_place_text',
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this model instance.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the instance was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the instance was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='ACTIVE', help_text='Status of the instance, typically used for soft deletion.', max_length=20)),
                ('home_banner', models.TextField(blank=True, help_text='Content of home tab banner for the user')),
                ('travel_guide', models.TextField(blank=True, help_text='Content of travel guide tab for the user')),
                ('about_me', models.TextField(blank=True, help_text='Content of about me tab for the user')),
                ('visited_place', models.TextField(blank=True, help_text='Content of visited place tab for the user')),
                ('gallery', models.TextField(blank=True, help_text='Content of gallery tab for the user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this model instance.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the instance was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the instance was last updated.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='ACTIVE', help_text='Status of the instance, typically used for soft deletion.', max_length=20)),
                ('home', models.URLField(blank=True, help_text='URL to the home section banner', max_length=500)),
                ('home_travel', models.URLField(blank=True, help_text='URL to the home travel section banner', max_length=500)),
                ('newsletter', models.URLField(blank=True, help_text='URL to the newsletter section banner', max_length=500)),
                ('contact', models.URLField(blank=True, help_text='URL to the contact section banner', max_length=500)),
                ('about', models.URLField(blank=True, help_text='URL to the about section banner', max_length=500)),
                ('visited_place', models.URLField(blank=True, help_text='URL to the visited place section banner', max_length=500)),
                ('visited_place_explore', models.URLField(blank=True, help_text='URL to the visited place explore section banner', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
